spring:
  application:
    name: store-winrecord
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: winrecord
  jpa:
    properties:
      hibernate:
        default_schema: winrecord

management:
  endpoints:
    web:
      base-path: /winrecord/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

store:
  account:
    url: http://localhost:8080 # Substitua pela URL real do serviço de contas


springdoc:
  api-docs:
    path: /winrecord/v3/api-docs
  swagger-ui:
    path: /winrecord/swagger-ui.html
  version: 3.0.0
