apiVersion: v1
kind: Service
metadata:
  name: tournamentmanager
  labels:
    name: tournamentmanager
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tournamentmanager